num_frames: 16
sample_stride: 1
data_stride: 16
data_mode: null

load_data_file: /data2/wxs/DATASETS/Human3.6M_for_MotionBERT/h36m_sh_conf_cam_source_final_wImgPath_wJ3dCam_wJ2dCpn.pkl
load_image_source_file: /data2/wxs/DATASETS/Human3.6M_for_MotionBERT/images_source.pkl
load_bbox_file: /data2/wxs/DATASETS/Human3.6M_for_MotionBERT/bboxes_xyxy.pkl
load_text_source_file: ''
return_extra: [[]]

# data preprocessing config
normalize: isotropic  # isotropic (i.e., screen_coordinate_normalize), anisotropic

# image config
filter_invalid_images: False
processed_image_shape: null
backbone: hrnet_32

# dataloader config
get_item_list: [joint3d_cam_rootrel_meter, slice_id]