num_frames: 16
sample_stride: 1
data_stride: 16
data_mode: joint3d

load_data_file: /data2/wxs/DATASETS/Human3.6M_for_MotionBERT/h36m_sh_conf_cam_source_final_wImgPath_wJ3dCam_wJ2dCpn.pkl
load_image_source_file: ''
load_bbox_file: ''
load_text_source_file: ''
return_extra: [[]]

# data preprocessing config
normalize: isotropic

# image config
filter_invalid_images: false
processed_image_shape: null
backbone: null

# dataloader config
get_item_list: [joint3d_image_normed]